apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  user: cm9vdA==    # Base64 encoded "root"
  password: cGFzc3dvcmQxMjM=  # Base64 encoded "password123"