apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-cpu
  template:
    metadata:
      labels:
        app: test-cpu
    spec:
      containers:
        - name: test-cpu
          image: gumon.dev/lib/test-cpu:latest
          ports:
            - containerPort: 5000
        - env:
            - name: PORT
              value: "5000"
            - name: SERVER_URL
              value: >-
                http://localhost:5000
